# Generated by Django 4.1.7 on 2023-03-21 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('Address', models.CharField(max_length=512)),
                ('contact', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/images')),
                ('name', models.CharField(max_length=50)),
                ('food_type', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('qnt', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cloths',
            fields=[
                ('cloth_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='static/images')),
                ('name', models.CharField(max_length=50)),
                ('cloth_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('qnt', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
