# Generated by Django 4.1.7 on 2023-03-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(default='12', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cloths',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
