# Generated by Django 4.1.7 on 2023-03-21 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donations', '0002_request_request_type_alter_cloths_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='Donation_Request',
        ),
    ]
