# Generated by Django 4.1.7 on 2023-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_rename_request_donation_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation_request',
            name='donate_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cloths',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
