# Generated by Django 4.1.7 on 2023-04-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_donation_request_donate_status_alter_cloths_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='donate',
            field=models.BooleanField(default=False),
        ),
    ]
